FROM rocm/pytorch:rocm5.5_ubuntu20.04_py3.8_pytorch_1.12.1

# Install pytorch (15.7.23)
# ENV HSA_OVERRIDE_GFX_VERSION=11.0.0

COPY /pytorch /pytorch_arch

RUN python3 -m pip uninstall torch torchvision torchaudio -y

#RUN python3 -m pip install --pre torch torchvision torchaudio --index-#url https://download.pytorch.org/whl/nightly/rocm5.5

RUN python3 -m pip install /pytorch_arch/torch-2.1.0.dev20230716+rocm5.5-cp38-cp38-linux_x86_64.whl


WORKDIR /project

COPY docker_requirements.txt /project/docker_requirements.txt

RUN python --version

RUN which python

RUN python -m pip install -r /project/docker_requirements.txt

RUN python3 -m pip install torchinfo

RUN echo "Done"
